# publish-nuget.yml
name: Publish NuGet Package on Release Publish

on:
  release:
    types: [published]

jobs:
  Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Release Version Environment Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"

      - name: Build, Test, and Publish NuGet
        uses: wahinekai/actions-publish-nuget@v3.0.1
        with:
          version: ${{ env.RELEASE_VERSION }}
          project-path: src/MemberDatabaseDTO/MemberDatabaseDTO.csproj
          solution-path: src/MemberDatabaseDTO.sln
          nuget-feed-password: ${{ secrets.PACKAGES_TOKEN }}
